name: diary_of_teacher
description: Application that allows you to keep a diary, especially about students, lessons and more.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.0+4
  google_sign_in: ^4.0.1+1
  image_picker: ^0.5.0+3
  shared_preferences: ^0.5.1+1
  cloud_firestore: ^0.9.5+2
  firebase_storage: ^2.1.0+1
  fluttertoast: ^3.0.1
  connectivity: ^0.4.2
  meta: ^1.1.6
  flutter_bloc: ^0.7.0
  bloc: ^0.9.3
  equatable: ^0.2.2
  flutter_calendar_carousel: ^1.3.15
  decimal: ^0.3.3
  flutter_datetime_picker: ^1.1.3
  flutter_advanced_networkimage: ^0.4.13


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Neucha
      fonts:
        - asset: assets/fonts/Neucha.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
        - asset: assets/fonts/RobotoCondensed-LightItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          style: italic


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700